CREATE SCHEMA WEDDING;
SET SCHEMA WEDDING;

CREATE TABLE FOOD (
  ID int NOT NULL,
  DESCRIPTION varchar(150) NOT NULL,
  TYPE varchar(25) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE GUEST (
  ID int NOT NULL,
  ATTENDANCE bit(1) DEFAULT NULL,
  DIETARY_COMMENTS varchar(255) DEFAULT NULL,
  DIETARY_CONCERNS bit(1) DEFAULT NULL,
  FIRST_NAME varchar(40) NOT NULL,
  INVITED_PERSON bit(1) DEFAULT NULL,
  LAST_NAME varchar(40) NOT NULL,
  FOOD_ID int DEFAULT NULL,
  INVITE_ID int NOT NULL,
  INVITEDPERSON bit(1) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE INVITATION (
  ID int NOT NULL,
  INVITATION_CODE varchar(255) NOT NULL,
  MAX_GUESTS int NOT NULL,
  PRIMARY KEY (ID)
);